// <auto-generated />
using System;
using Aviate.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Aviate.Migrations
{
    [DbContext(typeof(NotificationContext))]
    [Migration("20240627143850_NotificationContextMig1")]
    partial class NotificationContextMig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aviate.Models.DatabaseNotifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Action");

                    b.Property<bool>("Processed")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("processed");

                    b.Property<string>("TableName")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TableName");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Timestamp");

                    b.Property<string>("alteringRows")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AlteringRows");

                    b.Property<int?>("rowId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Row_Id");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
